Rules:
  - object_path: asdfasdf/.* # Path in the CCDB to a certain object
    delay: 1440              # Delay in minutes during which a new object is not touched. (1 day)
    policy: 1_per_hour       # name of the policy to apply, must correspond to a python script.
  - object_path: QcTask/example
    delay: 120
    policy: 1_per_hour
    
Ccdb:
   Url: http://UPDATEME.cern.ch:8080