language: cpp
matrix:
  include:
    - os: linux
      dist: xenial
      env: TOOL=clang-format
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-format-8
      compiler: clang
script:
  - if [[ $TOOL == "clang-format" ]] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      cd $TRAVIS_BUILD_DIR;
      BASE_COMMIT=$(git rev-parse $TRAVIS_BRANCH);
      COMMIT_FILES=$(git diff --name-only $BASE_COMMIT | grep -i -v LinkDef);
      RESULT_OUTPUT="$(git-clang-format-8 --commit $BASE_COMMIT --diff --binary `which clang-format-8` $COMMIT_FILES)";
      if [ "$RESULT_OUTPUT" == "no modified files to format" ] || [ "$RESULT_OUTPUT" == "clang-format did not modify any files" ] ; then
        exit 0;
      else
        echo "$RESULT_OUTPUT";
        exit 1;
      fi
    fi
notifications:
  email: false
