// Copyright CERN and copyright holders of ALICE O2. This software is
// distributed under the terms of the GNU General Public License v3 (GPL
// Version 3), copied verbatim in the file "COPYING".
//
// See http://alice-o2.web.cern.ch/license for full licensing information.
//
// In applying this license CERN does not waive the privileges and immunities
// granted to it by virtue of its status as an Intergovernmental Organization
// or submit itself to any jurisdiction.

#ifndef QUALITYCONTROL_DATASOURCESPEC_H
#define QUALITYCONTROL_DATASOURCESPEC_H

///
/// \file   DataSourceSpec.h
/// \author Piotr Konopka
///

#include <string>
#include <vector>
#include <Framework/InputSpec.h>
#include <type_traits>

namespace o2::quality_control::core
{

enum class DataSourceType {
  DataSamplingPolicy,
  Direct,
  Task,
  TaskMovingWindow,
  Check,
  Aggregator,
  PostProcessingTask,
  LateTask,
  ExternalTask,
  Invalid
};

constexpr char CharIdFrom(DataSourceType type)
{
  switch (type) {
    case DataSourceType::DataSamplingPolicy:
    case DataSourceType::Direct:
    case DataSourceType::ExternalTask:
      throw std::invalid_argument("Provided data source type is not generated by QC, cannot provide a corresponding character");
    case DataSourceType::Task:
      return 'Q';
    case DataSourceType::TaskMovingWindow:
      return 'W';
    case DataSourceType::Check:
      return 'C';
    case DataSourceType::Aggregator:
      return 'A';
    case DataSourceType::PostProcessingTask:
      return 'P';
    case DataSourceType::LateTask:
      return 'L';
    default:
      throw std::invalid_argument("Unrecognized data source type");
  }
}

// this should allow us to represent all data sources which come from DPL (and maybe CCDB).
struct DataSourceSpec {
  explicit DataSourceSpec(DataSourceType type = DataSourceType::Invalid);

  template <class... DataSourceType>
  bool isOneOf(DataSourceType... dataSourceType) const
  {
    return (... || (dataSourceType == type));
  }

  DataSourceType type;
  std::string id;
  std::string name;
  std::vector<framework::InputSpec> inputs;
  std::vector<std::string> subInputs; // can be MO or QO names
};

} // namespace o2::quality_control::core

#endif //QUALITYCONTROL_DATASOURCESPEC_H
